version = 0.1

[default.deploy.parameters]
stack_name = "serverlesspresso-publisher-service"
resolve_s3 = true
s3_prefix = "serverlesspresso-publisher-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EventBusName=\"serverlesspresso-dev\" IoTEndpoint=\"a32lhsj7z5zzai-ats.iot.us-east-1.amazonaws.com\" Source=\"awsserverlessda.serverlesspresso\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
