version = 0.1

[default.deploy.parameters]
stack_name = "serverlesspresso-order-processing"
resolve_s3 = true
s3_prefix = "serverlesspresso-order-processing"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EventBusName=\"serverlesspresso-dev\" ConfigTableName=\"serverlesspresso-config-dev\" CountingTableName=\"serverlesspresso-counting-dev\" Source=\"awsserverlessda.serverlesspresso\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
